/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSiteAssetsSplatRouteImport } from './routes/api/site-assets/$'
import { Route as ApiOpsGuestLeadRouteImport } from './routes/api/ops/guest-lead'
import { Route as ApiOnyxStatusRouteImport } from './routes/api/onyx/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteAssetsSplatRoute = ApiSiteAssetsSplatRouteImport.update({
  id: '/api/site-assets/$',
  path: '/api/site-assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsGuestLeadRoute = ApiOpsGuestLeadRouteImport.update({
  id: '/api/ops/guest-lead',
  path: '/api/ops/guest-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnyxStatusRoute = ApiOnyxStatusRouteImport.update({
  id: '/api/onyx/status',
  path: '/api/onyx/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/onyx/status': typeof ApiOnyxStatusRoute
  '/api/ops/guest-lead': typeof ApiOpsGuestLeadRoute
  '/api/site-assets/$': typeof ApiSiteAssetsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/onyx/status': typeof ApiOnyxStatusRoute
  '/api/ops/guest-lead': typeof ApiOpsGuestLeadRoute
  '/api/site-assets/$': typeof ApiSiteAssetsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/onyx/status': typeof ApiOnyxStatusRoute
  '/api/ops/guest-lead': typeof ApiOpsGuestLeadRoute
  '/api/site-assets/$': typeof ApiSiteAssetsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/onyx/status'
    | '/api/ops/guest-lead'
    | '/api/site-assets/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/onyx/status' | '/api/ops/guest-lead' | '/api/site-assets/$'
  id:
    | '__root__'
    | '/'
    | '/api/onyx/status'
    | '/api/ops/guest-lead'
    | '/api/site-assets/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiOnyxStatusRoute: typeof ApiOnyxStatusRoute
  ApiOpsGuestLeadRoute: typeof ApiOpsGuestLeadRoute
  ApiSiteAssetsSplatRoute: typeof ApiSiteAssetsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-assets/$': {
      id: '/api/site-assets/$'
      path: '/api/site-assets/$'
      fullPath: '/api/site-assets/$'
      preLoaderRoute: typeof ApiSiteAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/guest-lead': {
      id: '/api/ops/guest-lead'
      path: '/api/ops/guest-lead'
      fullPath: '/api/ops/guest-lead'
      preLoaderRoute: typeof ApiOpsGuestLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onyx/status': {
      id: '/api/onyx/status'
      path: '/api/onyx/status'
      fullPath: '/api/onyx/status'
      preLoaderRoute: typeof ApiOnyxStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiOnyxStatusRoute: ApiOnyxStatusRoute,
  ApiOpsGuestLeadRoute: ApiOpsGuestLeadRoute,
  ApiSiteAssetsSplatRoute: ApiSiteAssetsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
